import archiver from "archiver";
import { db } from "../db";
import { spriteSheets, animations, tilesets, environments, characters } from "@shared/schema";
import { eq } from "drizzle-orm";
import { generatePhaserTemplate } from "./phaser-template";
import { Readable } from "stream";

interface BundleAsset {
  name: string;
  fileUrl: string;
  type: "sprite" | "tileset" | "atlas";
}

const README_CONTENT = `# Phaser Game Export

Generated by Sneebly.

## Setup

1. Install dependencies:
   \`\`\`bash
   npm install
   \`\`\`

2. Start the dev server:
   \`\`\`bash
   npm run dev
   \`\`\`

3. Build for production:
   \`\`\`bash
   npm run build
   \`\`\`

## Structure

- \`/src\` — Generated Phaser game code (scenes, config, preloader)
- \`/assets/sprites\` — Sprite sheet PNGs
- \`/assets/tilesets\` — Tileset images
- \`/assets/atlases\` — Atlas JSON descriptors

## Notes

- This project uses Phaser 3.
- Asset paths in the preloader are relative to the project root.
- Edit \`src/config.ts\` to change game dimensions, physics, etc.
`;

async function fetchAssetBuffer(fileUrl: string): Promise<Buffer | null> {
  try {
    if (fileUrl.startsWith("http://") || fileUrl.startsWith("https://")) {
      const response = await fetch(fileUrl);
      if (!response.ok) {
        console.error(`Failed to fetch asset: ${fileUrl} (${response.status})`);
        return null;
      }
      const arrayBuffer = await response.arrayBuffer();
      return Buffer.from(arrayBuffer);
    }

    // Local file path — read from disk
    const fs = await import("fs/promises");
    const path = await import("path");
    const resolved = path.resolve(fileUrl);
    return await fs.readFile(resolved);
  } catch (err) {
    console.error(`Error fetching asset ${fileUrl}:`, err);
    return null;
  }
}

function getAssetDir(type: BundleAsset["type"]): string {
  switch (type) {
    case "sprite":
      return "assets/sprites";
    case "tileset":
      return "assets/tilesets";
    case "atlas":
      return "assets/atlases";
  }
}

function sanitizeFilename(name: string): string {
  return name.replace(/[^a-zA-Z0-9._-]/g, "_");
}

export async function buildBundle(projectId: number): Promise<Buffer> {
  // 1. Query all related assets from DB
  const [projectSprites, projectAnimations, projectTilesets, projectEnvironments, projectCharacters] =
    await Promise.all([
      db.select().from(spriteSheets).where(eq(spriteSheets.projectId, String(projectId))),
      db.select().from(animations).where(eq(animations.projectId, String(projectId))),
      db.select().from(tilesets).where(eq(tilesets.projectId, String(projectId))),
      db.select().from(environments).where(eq(environments.projectId, String(projectId))),
      db.select().from(characters).where(eq(characters.projectId, String(projectId))),
    ]);

  // 2. Collect all downloadable assets
  const bundleAssets: BundleAsset[] = [];

  for (const sprite of projectSprites) {
    if (sprite.fileUrl) {
      bundleAssets.push({
        name: sanitizeFilename(sprite.animationState || `sprite_${sprite.id}`) + ".png",
        fileUrl: sprite.fileUrl,
        type: "sprite",
      });
    }
    // If there's an atlas JSON URL, grab that too
    if ((sprite as any).atlasUrl) {
      bundleAssets.push({
        name: sanitizeFilename(sprite.animationState || `sprite_${sprite.id}`) + ".json",
        fileUrl: (sprite as any).atlasUrl,
        type: "atlas",
      });
    }
  }

  for (const tileset of projectTilesets) {
    if (tileset.fileUrl) {
      bundleAssets.push({
        name: sanitizeFilename(tileset.name || `tileset_${tileset.id}`) + ".png",
        fileUrl: tileset.fileUrl,
        type: "tileset",
      });
    }
  }

  // Characters and environments may also have image URLs
  for (const character of projectCharacters) {
    if ((character as any).spriteUrl) {
      bundleAssets.push({
        name: sanitizeFilename(character.name || `character_${character.id}`) + ".png",
        fileUrl: (character as any).spriteUrl,
        type: "sprite",
      });
    }
  }

  for (const env of projectEnvironments) {
    if ((env as any).backgroundUrl) {
      bundleAssets.push({
        name: sanitizeFilename(env.name || `environment_${env.id}`) + ".png",
        fileUrl: (env as any).backgroundUrl,
        type: "tileset",
      });
    }
  }

  // 3. Generate Phaser template code
  const templateFiles = generatePhaserTemplate({
    projectId,
    sprites: projectSprites,
    animations: projectAnimations,
    tilesets: projectTilesets,
    environments: projectEnvironments,
    characters: projectCharacters,
    assets: bundleAssets.map((a) => ({
      key: a.name.replace(/\.[^.]+$/, ""),
      path: `${getAssetDir(a.type)}/${a.name}`,
      type: a.type,
    })),
  });

  // 4. Build the ZIP
  return new Promise<Buffer>(async (resolve, reject) => {
    const archive = archiver("zip", { zlib: { level: 9 } });
    const chunks: Buffer[] = [];

    archive.on("data", (chunk: Buffer) => chunks.push(chunk));
    archive.on("end", () => resolve(Buffer.concat(chunks)));
    archive.on("error", (err: Error) => reject(err));

    // Add generated source files
    for (const file of templateFiles) {
      archive.append(file.content, { name: `src/${file.filename}` });
    }

    // Add README
    archive.append(README_CONTENT, { name: "README.md" });

    // Fetch and add asset files
    for (const asset of bundleAssets) {
      const buffer = await fetchAssetBuffer(asset.fileUrl);
      if (buffer) {
        const dir = getAssetDir(asset.type);
        archive.append(buffer, { name: `${dir}/${asset.name}` });
      } else {
        console.warn(`Skipping asset ${asset.name} — could not fetch from ${asset.fileUrl}`);
      }
    }

    archive.finalize();
  });
}
